name: Update TamilMV Feed

on:
  schedule:
    - cron: '0 */5 * * *' # Runs every 5 hours
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-feed:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Install curl
        run: sudo apt-get install -y curl
        
      - name: Fetch content
        run: curl -o tamilmv_feed.html https://test1.proxyboy.site/
        
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add tamilmv_feed.html
          git commit -m "Update tamilmv_feed.html" || echo "No changes to commit"
        
      - name: Push changes
        run: git push
